### ISSUE TITLE
why user managment , adapters is lost  in ui ?

### ISSUE THREAD

**Issue by magixmin** [mainflux/ui#161]
hi man .
after i upgrade the version 
why user managment , adapters is lost  in ui ?

**Comment by manuio** [comment]
It's because users groups features are still in progress in Mainflux repo. We decided to create an experimental version with unstable implementations. You can try building your own image with `make ui-experimental`. You can then rename the image tag (`docker tag mainflux/ui-experimental mainflux/ui`) or modify your docker-compose to use it.

**Comment by magixmin** [comment]
Go 。Looking forward to your outstanding features。
